"""Principal-bound storage for authenticated remote MCP media.

The remote server must never hand an HTTP caller a pod path.  This module keeps
opaque metadata in SQLite and bytes in a private sibling directory.  It has no
dependency on the MCP SDK so storage, quota, expiry, and recovery stay directly
unit-testable (and the base Venice import graph remains dependency-free).
"""
from __future__ import annotations

import hashlib
import math
import os
import re
import secrets
import shutil
import sqlite3
import stat
import tempfile
import threading
import time
import urllib.parse
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


DEFAULT_TTL_SECONDS = 24 * 60 * 60
DEFAULT_MAX_OBJECTS = 100
DEFAULT_PRINCIPAL_MAX_BYTES = 1024 * 1024 * 1024
DEFAULT_GLOBAL_MAX_BYTES = 4 * 1024 * 1024 * 1024
DEFAULT_MAX_PENDING_JOBS = 4
DEFAULT_GLOBAL_MAX_PENDING_JOBS = 16
DEFAULT_MCP_READ_MAX_BYTES = 32 * 1024 * 1024

INPUT_MAX_BYTES = {
    "image": 25 * 1024 * 1024,
    "audio": 15 * 1024 * 1024,
    "video": 50 * 1024 * 1024,
}
OUTPUT_MAX_BYTES = {
    "image": 25 * 1024 * 1024,
    "audio": 64 * 1024 * 1024,
    "video": 512 * 1024 * 1024,
}

_ID_RE = re.compile(r"[A-Za-z0-9_-]{43}\Z")
_SNIFF_BYTES = 64


class MediaStoreError(RuntimeError):
    """The private media store is unavailable or inconsistent."""


class MediaNotFound(MediaStoreError):
    """An object is missing, expired, malformed, or owned by somebody else."""


class MediaQuotaError(MediaStoreError):
    """A bounded object/job quota would be exceeded."""


class MediaValidationError(MediaStoreError):
    """Uploaded/generated bytes do not meet the declared media contract."""


@dataclass(frozen=True)
class MediaRecord:
    id: str
    owner: str
    kind: str
    mime_type: str
    size: int
    filename: str
    sha256: str
    created_at: float
    expires_at: float
    path: Path


@dataclass(frozen=True)
class JobRecord:
    id: str
    owner: str
    backend_id: str
    kind: str
    model: str
    status: str
    resource_id: Optional[str]
    reservation_id: Optional[str]
    cost: Optional[float]
    created_at: float
    expires_at: float
    error: Optional[str]


def principal_key(*, issuer: str, subject: str, client_id: str) -> str:
    """Return a non-reversible stable partition key for one OAuth principal."""
    values = (issuer, subject, client_id)
    if any(not isinstance(value, str) or not value for value in values):
        raise MediaStoreError("authenticated issuer, subject, and client identity are required")
    return hashlib.sha256("\0".join(values).encode("utf-8")).hexdigest()


def sniff_media(prefix: bytes) -> tuple[str, str]:
    """Return ``(kind, mime)`` for the deliberately small accepted container set."""
    if prefix.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image", "image/png"
    if prefix.startswith(b"\xff\xd8\xff"):
        return "image", "image/jpeg"
    if prefix.startswith((b"GIF87a", b"GIF89a")):
        return "image", "image/gif"
    if len(prefix) >= 12 and prefix[:4] == b"RIFF" and prefix[8:12] == b"WEBP":
        return "image", "image/webp"
    if prefix.startswith(b"fLaC"):
        return "audio", "audio/flac"
    if prefix.startswith(b"OggS"):
        return "audio", "audio/ogg"
    if len(prefix) >= 12 and prefix[:4] == b"RIFF" and prefix[8:12] == b"WAVE":
        return "audio", "audio/wav"
    if prefix.startswith(b"ID3"):
        return "audio", "audio/mpeg"
    if len(prefix) >= 2 and prefix[0] == 0xFF:
        if prefix[1] & 0xF6 == 0xF0:
            return "audio", "audio/aac"
        if prefix[1] & 0xE0 == 0xE0 and prefix[1] & 0x06:
            return "audio", "audio/mpeg"
    if prefix.startswith(b"\x1aE\xdf\xa3"):
        return "video", "video/webm"
    if len(prefix) >= 12 and prefix[4:8] == b"ftyp":
        if prefix[8:12] == b"qt  ":
            return "video", "video/quicktime"
        # M4A/MP4 audio brand values are distinguishable enough for the formats
        # Venice emits, while all other ftyp containers are treated as video.
        if prefix[8:12] in (b"M4A ", b"M4B ", b"M4P "):
            return "audio", "audio/mp4"
        return "video", "video/mp4"
    raise MediaValidationError("content is not a recognized image, audio, or video container")


def _safe_filename(value: Optional[str], *, kind: str, mime_type: str) -> str:
    extensions = {
        "image/png": ".png", "image/jpeg": ".jpg", "image/gif": ".gif",
        "image/webp": ".webp", "audio/flac": ".flac", "audio/ogg": ".ogg",
        "audio/wav": ".wav", "audio/mpeg": ".mp3", "audio/aac": ".aac",
        "audio/mp4": ".m4a", "video/webm": ".webm", "video/mp4": ".mp4",
        "video/quicktime": ".mov",
    }
    fallback = f"venice-{kind}{extensions.get(mime_type, '.bin')}"
    if not value:
        return fallback
    base = os.path.basename(value).strip()
    if (
        not base
        or len(base.encode("utf-8")) > 200
        or base in (".", "..")
        or any(ord(char) < 32 for char in base)
    ):
        return fallback
    return base


class RemoteMediaStore:
    """A bounded single-process SQLite/filesystem media store."""

    def __init__(
        self,
        root,
        *,
        public_origin: str,
        ttl_seconds: int = DEFAULT_TTL_SECONDS,
        max_objects: int = DEFAULT_MAX_OBJECTS,
        principal_max_bytes: int = DEFAULT_PRINCIPAL_MAX_BYTES,
        global_max_bytes: int = DEFAULT_GLOBAL_MAX_BYTES,
        max_pending_jobs: int = DEFAULT_MAX_PENDING_JOBS,
        global_max_pending_jobs: int = DEFAULT_GLOBAL_MAX_PENDING_JOBS,
        mcp_read_max_bytes: int = DEFAULT_MCP_READ_MAX_BYTES,
        clock=time.time,
    ):
        self.root = Path(root)
        forbidden_roots = {
            Path("/"), Path(tempfile.gettempdir()).resolve(), Path.home().resolve(),
        }
        if not self.root.is_absolute():
            raise MediaStoreError("media directory must be an absolute dedicated directory")
        if self.root.resolve() in forbidden_roots:
            raise MediaStoreError("media directory is too broad; use a dedicated subdirectory")
        self.public_origin = str(public_origin).rstrip("/")
        self.ttl_seconds = self._positive(ttl_seconds, "media TTL")
        self.max_objects = self._positive(max_objects, "media object limit")
        self.principal_max_bytes = self._positive(
            principal_max_bytes, "per-principal media byte limit"
        )
        self.global_max_bytes = self._positive(
            global_max_bytes, "global media byte limit"
        )
        self.max_pending_jobs = self._positive(max_pending_jobs, "pending job limit")
        self.global_max_pending_jobs = self._positive(
            global_max_pending_jobs, "global pending job limit"
        )
        self.mcp_read_max_bytes = self._positive(
            mcp_read_max_bytes, "MCP resource read limit"
        )
        self._clock = clock
        self._lock = threading.RLock()
        self.blobs = self.root / "blobs"
        self.tmp = self.root / "tmp"
        self.db_path = self.root / "media.sqlite3"
        self._initialize()

    @staticmethod
    def _positive(value, label: str) -> int:
        try:
            number = int(value)
        except (TypeError, ValueError):
            raise MediaStoreError(f"{label} must be an integer") from None
        if number <= 0:
            raise MediaStoreError(f"{label} must be greater than zero")
        return number

    def _initialize(self) -> None:
        for path in (self.root, self.blobs, self.tmp):
            try:
                if path.exists() and (path.is_symlink() or not path.is_dir()):
                    raise MediaStoreError(f"media path is not a private directory: {path}")
                path.mkdir(parents=True, exist_ok=True, mode=0o700)
                os.chmod(path, 0o700)
            except OSError as exc:
                raise MediaStoreError(f"cannot initialize media directory: {exc}") from None
        with self._connect() as db:
            db.executescript(
                """
                CREATE TABLE IF NOT EXISTS resources (
                    id TEXT PRIMARY KEY, owner TEXT NOT NULL, kind TEXT NOT NULL,
                    mime_type TEXT NOT NULL, size INTEGER NOT NULL,
                    filename TEXT NOT NULL, sha256 TEXT NOT NULL,
                    created_at REAL NOT NULL, expires_at REAL NOT NULL
                );
                CREATE INDEX IF NOT EXISTS resources_owner ON resources(owner);
                CREATE INDEX IF NOT EXISTS resources_expiry ON resources(expires_at);
                CREATE TABLE IF NOT EXISTS reservations (
                    id TEXT PRIMARY KEY, owner TEXT NOT NULL, bytes INTEGER NOT NULL,
                    created_at REAL NOT NULL, expires_at REAL NOT NULL
                );
                CREATE INDEX IF NOT EXISTS reservations_owner ON reservations(owner);
                CREATE TABLE IF NOT EXISTS jobs (
                    id TEXT PRIMARY KEY, owner TEXT NOT NULL, backend_id TEXT NOT NULL,
                    kind TEXT NOT NULL, model TEXT NOT NULL, status TEXT NOT NULL,
                    resource_id TEXT, reservation_id TEXT, cost REAL,
                    created_at REAL NOT NULL, expires_at REAL NOT NULL, error TEXT
                );
                CREATE INDEX IF NOT EXISTS jobs_owner ON jobs(owner);
                CREATE TABLE IF NOT EXISTS backend_urls (
                    owner TEXT NOT NULL, backend_id TEXT NOT NULL, model TEXT NOT NULL,
                    download_url TEXT NOT NULL, created_at REAL NOT NULL,
                    expires_at REAL NOT NULL,
                    PRIMARY KEY(owner, backend_id, model)
                );
                """
            )
        try:
            os.chmod(self.db_path, 0o600)
        except OSError:
            pass
        self.reconcile()

    def _connect(self):
        try:
            db = sqlite3.connect(self.db_path, timeout=5)
            db.row_factory = sqlite3.Row
            db.execute("PRAGMA foreign_keys=ON")
            db.execute("PRAGMA journal_mode=WAL")
            db.execute("PRAGMA busy_timeout=5000")
            return db
        except sqlite3.Error as exc:
            raise MediaStoreError(f"cannot open media metadata: {exc}") from None

    @staticmethod
    def valid_id(value: str) -> bool:
        return isinstance(value, str) and bool(_ID_RE.fullmatch(value))

    @staticmethod
    def _new_id() -> str:
        return secrets.token_urlsafe(32)

    def resource_uri(self, resource_id: str) -> str:
        if not self.valid_id(resource_id):
            raise MediaNotFound("media resource not found")
        return f"{self.public_origin}/media/{resource_id}"

    def id_from_uri(self, uri: str) -> str:
        prefix = f"{self.public_origin}/media/"
        if not isinstance(uri, str) or not uri.startswith(prefix):
            raise MediaNotFound("media resource not found")
        resource_id = uri[len(prefix):]
        if "/" in resource_id or "?" in resource_id or "#" in resource_id:
            raise MediaNotFound("media resource not found")
        if not self.valid_id(resource_id):
            raise MediaNotFound("media resource not found")
        return resource_id

    def new_temp_path(self) -> Path:
        fd, name = tempfile.mkstemp(prefix=".media-", suffix=".part", dir=self.tmp)
        os.close(fd)
        os.chmod(name, 0o600)
        return Path(name)

    def new_work_dir(self) -> Path:
        return Path(tempfile.mkdtemp(prefix="work-", dir=self.tmp))

    def reserve(self, owner: str, byte_count: int, *, count: int = 1) -> list[str]:
        byte_count = self._positive(byte_count, "reservation bytes")
        count = self._positive(count, "reservation count")
        per_object = byte_count
        now = float(self._clock())
        with self._lock, self._connect() as db:
            self._prune_db(db, now)
            owner_objects = db.execute(
                "SELECT COUNT(*) FROM resources WHERE owner=?", (owner,)
            ).fetchone()[0]
            owner_reserved = db.execute(
                "SELECT COUNT(*) FROM reservations WHERE owner=?", (owner,)
            ).fetchone()[0]
            if owner_objects + owner_reserved + count > self.max_objects:
                raise MediaQuotaError("per-principal media object limit would be exceeded")
            owner_bytes = db.execute(
                "SELECT COALESCE(SUM(size),0) FROM resources WHERE owner=?", (owner,)
            ).fetchone()[0]
            owner_bytes += db.execute(
                "SELECT COALESCE(SUM(bytes),0) FROM reservations WHERE owner=?", (owner,)
            ).fetchone()[0]
            requested = per_object * count
            if owner_bytes + requested > self.principal_max_bytes:
                raise MediaQuotaError("per-principal media byte limit would be exceeded")
            global_bytes = db.execute(
                "SELECT COALESCE(SUM(size),0) FROM resources"
            ).fetchone()[0]
            global_bytes += db.execute(
                "SELECT COALESCE(SUM(bytes),0) FROM reservations"
            ).fetchone()[0]
            if global_bytes + requested > self.global_max_bytes:
                raise MediaQuotaError("global media byte limit would be exceeded")
            ids = [self._new_id() for _ in range(count)]
            db.executemany(
                "INSERT INTO reservations VALUES(?,?,?,?,?)",
                [(rid, owner, per_object, now, now + self.ttl_seconds) for rid in ids],
            )
            return ids

    def release(self, owner: str, reservation_id: str) -> None:
        with self._lock, self._connect() as db:
            db.execute(
                "DELETE FROM reservations WHERE id=? AND owner=?",
                (reservation_id, owner),
            )

    def commit_file(
        self,
        owner: str,
        reservation_id: str,
        source,
        *,
        expected_kind: Optional[str] = None,
        declared_mime: Optional[str] = None,
        filename: Optional[str] = None,
        job_id: Optional[str] = None,
    ) -> MediaRecord:
        source = Path(source)
        try:
            if source.is_symlink():
                raise MediaValidationError("media content must not be a symbolic link")
            info = source.stat()
            if not stat.S_ISREG(info.st_mode) or info.st_size <= 0:
                raise MediaValidationError("media content must be a non-empty regular file")
            with source.open("rb") as handle:
                prefix = handle.read(_SNIFF_BYTES)
        except MediaValidationError:
            raise
        except OSError as exc:
            raise MediaStoreError(f"cannot read staged media: {exc}") from None
        kind, mime_type = sniff_media(prefix)
        if expected_kind is not None and kind != expected_kind:
            raise MediaValidationError(f"expected {expected_kind} content, received {kind}")
        if declared_mime:
            normalized = declared_mime.split(";", 1)[0].strip().lower()
            aliases = {"audio/mp3": "audio/mpeg", "image/jpg": "image/jpeg"}
            normalized = aliases.get(normalized, normalized)
            if normalized != mime_type:
                raise MediaValidationError(
                    f"declared content type {normalized!r} does not match {mime_type!r}"
                )

        now = float(self._clock())
        resource_id = self._new_id()
        destination = self.blobs / resource_id
        with self._lock, self._connect() as db:
            self._prune_db(db, now)
            reservation = db.execute(
                "SELECT bytes FROM reservations WHERE id=? AND owner=?",
                (reservation_id, owner),
            ).fetchone()
            if reservation is None:
                raise MediaQuotaError("media reservation is missing or expired")
            if job_id is not None:
                job = db.execute(
                    "SELECT id FROM jobs WHERE id=? AND owner=? AND status='processing' "
                    "AND reservation_id=?",
                    (job_id, owner, reservation_id),
                ).fetchone()
                if job is None:
                    raise MediaNotFound("media job not found")
            if info.st_size > reservation["bytes"]:
                raise MediaQuotaError("media output exceeded its reserved byte limit")
            digest = hashlib.sha256()
            try:
                with source.open("rb") as handle:
                    for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                        digest.update(chunk)
                os.replace(source, destination)
                os.chmod(destination, 0o600)
            except OSError as exc:
                raise MediaStoreError(f"cannot commit media content: {exc}") from None
            safe_name = _safe_filename(filename, kind=kind, mime_type=mime_type)
            try:
                db.execute(
                    "INSERT INTO resources VALUES(?,?,?,?,?,?,?,?,?)",
                    (
                        resource_id, owner, kind, mime_type, info.st_size, safe_name,
                        digest.hexdigest(), now, now + self.ttl_seconds,
                    ),
                )
                db.execute("DELETE FROM reservations WHERE id=?", (reservation_id,))
                if job_id is not None:
                    changed = db.execute(
                        "UPDATE jobs SET status='ready', resource_id=?, "
                        "reservation_id=NULL WHERE id=? AND owner=? AND status='processing'",
                        (resource_id, job_id, owner),
                    ).rowcount
                    if changed != 1:
                        raise MediaNotFound("media job not found")
            except (sqlite3.Error, MediaStoreError) as exc:
                try:
                    destination.unlink()
                except OSError:
                    pass
                if isinstance(exc, MediaStoreError):
                    raise
                raise MediaStoreError(f"cannot commit media metadata: {exc}") from None
        return self.get(owner, resource_id)

    def put_input(
        self,
        owner: str,
        source,
        *,
        declared_mime: Optional[str] = None,
        filename: Optional[str] = None,
        reservation_id: Optional[str] = None,
    ) -> MediaRecord:
        source = Path(source)
        try:
            with source.open("rb") as handle:
                kind, _mime = sniff_media(handle.read(_SNIFF_BYTES))
            size = source.stat().st_size
        except MediaStoreError:
            raise
        except OSError as exc:
            raise MediaStoreError(f"cannot inspect uploaded media: {exc}") from None
        limit = INPUT_MAX_BYTES[kind]
        if size <= 0 or size > limit:
            raise MediaValidationError(
                f"{kind} input is {size} bytes; limit is {limit} bytes"
            )
        reservation = reservation_id or self.reserve(owner, size)[0]
        try:
            return self.commit_file(
                owner, reservation, source, expected_kind=kind,
                declared_mime=declared_mime, filename=filename,
            )
        except Exception:
            self.release(owner, reservation)
            raise

    def get(self, owner: str, resource_id: str) -> MediaRecord:
        if not self.valid_id(resource_id):
            raise MediaNotFound("media resource not found")
        now = float(self._clock())
        with self._lock, self._connect() as db:
            self._prune_db(db, now)
            row = db.execute(
                "SELECT * FROM resources WHERE id=? AND owner=?",
                (resource_id, owner),
            ).fetchone()
        if row is None:
            raise MediaNotFound("media resource not found")
        path = self.blobs / resource_id
        try:
            info = path.stat()
        except OSError:
            raise MediaNotFound("media resource not found") from None
        if not stat.S_ISREG(info.st_mode) or path.is_symlink() or info.st_size != row["size"]:
            raise MediaNotFound("media resource not found")
        return MediaRecord(
            id=row["id"], owner=row["owner"], kind=row["kind"],
            mime_type=row["mime_type"], size=row["size"], filename=row["filename"],
            sha256=row["sha256"], created_at=row["created_at"],
            expires_at=row["expires_at"], path=path,
        )

    def get_uri(self, owner: str, uri: str) -> MediaRecord:
        return self.get(owner, self.id_from_uri(uri))

    def delete(self, owner: str, resource_id: str) -> None:
        if not self.valid_id(resource_id):
            raise MediaNotFound("media resource not found")
        with self._lock, self._connect() as db:
            row = db.execute(
                "SELECT id FROM resources WHERE id=? AND owner=?", (resource_id, owner)
            ).fetchone()
            if row is None:
                raise MediaNotFound("media resource not found")
            db.execute("DELETE FROM resources WHERE id=?", (resource_id,))
        try:
            (self.blobs / resource_id).unlink()
        except FileNotFoundError:
            pass
        except OSError as exc:
            raise MediaStoreError(f"cannot delete media content: {exc}") from None

    def create_job(
        self,
        owner: str,
        *,
        backend_id: str,
        kind: str,
        model: str,
        reservation_id: str,
        cost: Optional[float],
    ) -> JobRecord:
        if (
            kind not in ("sfx", "music", "video")
            or not isinstance(backend_id, str) or not backend_id or len(backend_id) > 512
            or not isinstance(model, str) or not model or len(model) > 256
        ):
            raise MediaStoreError("invalid remote media job")
        if cost is not None:
            try:
                cost = float(cost)
            except (TypeError, ValueError):
                raise MediaStoreError("invalid remote media job cost") from None
            if not math.isfinite(cost) or cost < 0:
                raise MediaStoreError("invalid remote media job cost")
        now = float(self._clock())
        with self._lock, self._connect() as db:
            self._prune_db(db, now)
            self._check_job_capacity(db, owner)
            reserved = db.execute(
                "SELECT id FROM reservations WHERE id=? AND owner=?",
                (reservation_id, owner),
            ).fetchone()
            if reserved is None:
                raise MediaQuotaError("job output reservation is missing or expired")
            job_id = self._new_id()
            db.execute(
                "INSERT INTO jobs VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",
                (
                    job_id, owner, backend_id, kind, model, "processing", None,
                    reservation_id, cost, now, now + self.ttl_seconds, None,
                ),
            )
        return self.get_job(owner, job_id)

    def check_job_capacity(self, owner: str) -> None:
        """Fail before a paid queue call when its job could not be recorded."""
        now = float(self._clock())
        with self._lock, self._connect() as db:
            self._prune_db(db, now)
            self._check_job_capacity(db, owner)

    def _check_job_capacity(self, db, owner: str) -> None:
        owner_count = db.execute(
            "SELECT COUNT(*) FROM jobs WHERE owner=? AND status='processing'", (owner,)
        ).fetchone()[0]
        global_count = db.execute(
            "SELECT COUNT(*) FROM jobs WHERE status='processing'"
        ).fetchone()[0]
        if owner_count >= self.max_pending_jobs:
            raise MediaQuotaError("per-principal pending job limit would be exceeded")
        if global_count >= self.global_max_pending_jobs:
            raise MediaQuotaError("global pending job limit would be exceeded")

    def get_job(self, owner: str, job_id: str) -> JobRecord:
        if not self.valid_id(job_id):
            raise MediaNotFound("media job not found")
        now = float(self._clock())
        with self._lock, self._connect() as db:
            self._prune_db(db, now)
            row = db.execute(
                "SELECT * FROM jobs WHERE id=? AND owner=?", (job_id, owner)
            ).fetchone()
        if row is None:
            raise MediaNotFound("media job not found")
        return JobRecord(
            id=row["id"], owner=row["owner"], backend_id=row["backend_id"],
            kind=row["kind"], model=row["model"], status=row["status"],
            resource_id=row["resource_id"], reservation_id=row["reservation_id"],
            cost=row["cost"], created_at=row["created_at"], expires_at=row["expires_at"],
            error=row["error"],
        )

    def finish_job(self, owner: str, job_id: str, resource_id: str) -> JobRecord:
        # Verify both resources before publishing the relationship.
        self.get(owner, resource_id)
        with self._lock, self._connect() as db:
            changed = db.execute(
                "UPDATE jobs SET status='ready', resource_id=?, reservation_id=NULL "
                "WHERE id=? AND owner=? AND status='processing'",
                (resource_id, job_id, owner),
            ).rowcount
            if not changed:
                row = db.execute(
                    "SELECT status, resource_id FROM jobs WHERE id=? AND owner=?",
                    (job_id, owner),
                ).fetchone()
                if row is None or row["status"] != "ready" or row["resource_id"] != resource_id:
                    raise MediaNotFound("media job not found")
        return self.get_job(owner, job_id)

    def fail_job(self, owner: str, job_id: str, message: str) -> JobRecord:
        with self._lock, self._connect() as db:
            row = db.execute(
                "SELECT reservation_id FROM jobs WHERE id=? AND owner=?", (job_id, owner)
            ).fetchone()
            if row is None:
                raise MediaNotFound("media job not found")
            if row["reservation_id"]:
                db.execute("DELETE FROM reservations WHERE id=?", (row["reservation_id"],))
            db.execute(
                "UPDATE jobs SET status='failed', reservation_id=NULL, error=? "
                "WHERE id=? AND owner=?",
                (str(message)[:500], job_id, owner),
            )
        return self.get_job(owner, job_id)

    def remember_download_url(self, owner: str, backend_id: str, model: str, url: str) -> None:
        if (
            not isinstance(url, str) or not url or len(url) > 16 * 1024
            or not isinstance(backend_id, str) or not backend_id or len(backend_id) > 512
            or not isinstance(model, str) or not model or len(model) > 256
        ):
            raise MediaStoreError("invalid private retrieval metadata")
        try:
            parsed = urllib.parse.urlsplit(url)
            parsed.port
        except ValueError:
            raise MediaStoreError("invalid private retrieval metadata") from None
        if (
            parsed.scheme != "https" or not parsed.hostname
            or parsed.username is not None or parsed.password is not None
            or parsed.fragment
        ):
            raise MediaStoreError("invalid private retrieval metadata")
        now = float(self._clock())
        with self._lock, self._connect() as db:
            db.execute(
                "INSERT OR REPLACE INTO backend_urls VALUES(?,?,?,?,?,?)",
                (owner, backend_id, model, url, now, now + self.ttl_seconds),
            )

    def lookup_download_url(self, owner: str, backend_id: str, model: str) -> Optional[str]:
        now = float(self._clock())
        with self._lock, self._connect() as db:
            self._prune_db(db, now)
            row = db.execute(
                "SELECT download_url FROM backend_urls "
                "WHERE owner=? AND backend_id=? AND model=?",
                (owner, backend_id, model),
            ).fetchone()
        return row["download_url"] if row is not None else None

    def forget_download_url(self, owner: str, backend_id: str, model: str) -> None:
        with self._lock, self._connect() as db:
            db.execute(
                "DELETE FROM backend_urls WHERE owner=? AND backend_id=? AND model=?",
                (owner, backend_id, model),
            )

    def reconcile(self) -> None:
        """Prune expired rows and remove incomplete/orphaned task-owned files."""
        now = float(self._clock())
        with self._lock, self._connect() as db:
            self._prune_db(db, now)
            live = {row[0] for row in db.execute("SELECT id FROM resources")}
            missing = [rid for rid in live if not (self.blobs / rid).is_file()]
            if missing:
                db.executemany("DELETE FROM resources WHERE id=?", [(rid,) for rid in missing])
                live.difference_update(missing)
        for path in self.tmp.iterdir():
            try:
                if path.is_dir():
                    shutil.rmtree(path)
                else:
                    path.unlink()
            except OSError:
                pass
        for path in self.blobs.iterdir():
            if path.name not in live:
                try:
                    path.unlink()
                except OSError:
                    pass

    def prune(self) -> None:
        with self._lock, self._connect() as db:
            self._prune_db(db, float(self._clock()))

    def _prune_db(self, db, now: float) -> None:
        expired = [
            row[0] for row in db.execute(
                "SELECT id FROM resources WHERE expires_at<=?", (now,)
            )
        ]
        db.execute("DELETE FROM resources WHERE expires_at<=?", (now,))
        db.execute("DELETE FROM reservations WHERE expires_at<=?", (now,))
        db.execute("DELETE FROM backend_urls WHERE expires_at<=?", (now,))
        expired_jobs = db.execute(
            "SELECT reservation_id FROM jobs WHERE expires_at<=?", (now,)
        ).fetchall()
        for row in expired_jobs:
            if row["reservation_id"]:
                db.execute("DELETE FROM reservations WHERE id=?", (row["reservation_id"],))
        db.execute("DELETE FROM jobs WHERE expires_at<=?", (now,))
        for resource_id in expired:
            try:
                (self.blobs / resource_id).unlink()
            except FileNotFoundError:
                pass
            except OSError:
                # Metadata removal is authoritative: an orphan never becomes readable.
                pass
