"""`venice completion [bash|zsh]` -- print a shell tab-completion script.

The script is *generated* by introspecting the live argparse parser
(`cli.build_parser()`), so it never drifts from the registered subcommands and
flags -- add a command and its completion updates for free. Emitted to stdout in
the kubectl/gh style so it needs no install hook and works for a
`pip install venice-cli` (which cannot run post-install scripts):

    # bash -- current shell:
    source <(venice completion bash)
    # bash -- persistent (also done automatically by install.sh for source installs):
    venice completion bash > ~/.local/share/bash-completion/completions/venice

    # zsh -- put it somewhere on your $fpath named `_venice`, e.g.:
    venice completion zsh > "${fpath[1]}/_venice"

Completion covers top-level commands, the nested actions of `config`/`secret`
(including the `secret` aliases `list`/`remove`), and each command's flag names.
It deliberately does not complete flag *values* -- keeping the emitted script
simple and shell-portable (no bash 4 associative arrays required).
"""
import argparse
import sys


# --------------------------------------------------------------------------- #
# Registration
# --------------------------------------------------------------------------- #
def register(subparsers) -> None:
    p = subparsers.add_parser(
        "completion",
        help="Print a bash or zsh tab-completion script for the venice CLI.",
        description=(
            "Emit a shell completion script to stdout, generated by introspecting "
            "the venice parser so it stays in sync with the real commands and "
            "flags. Load bash with `source <(venice completion bash)`; for zsh put "
            "the output on your $fpath as `_venice`."
        ),
    )
    p.add_argument(
        "shell", choices=("bash", "zsh"),
        help="Which shell to emit a completion script for.",
    )
    p.set_defaults(handler=_run)


def _run(args) -> int:
    # Local import: `cli` imports `commands` (which imports this module), so a
    # top-level `from ..cli import build_parser` would be a cycle.
    from ..cli import build_parser

    model = _walk_parser(build_parser())
    script = _bash_script(model) if args.shell == "bash" else _zsh_script(model)
    sys.stdout.write(script)
    return 0


# --------------------------------------------------------------------------- #
# Parser introspection (stdlib argparse internals)
# --------------------------------------------------------------------------- #
def _find_subparsers(parser):
    """The `_SubParsersAction` of `parser`, or None (no public accessor)."""
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _subcommands(action):
    """Canonical subcommands of a `_SubParsersAction`, in registration order.

    Aliases have no dedicated attribute on the pseudo-action (verified on 3.9-3.13);
    recover them by grouping `action.choices` (which contains an entry per alias) by
    the parser object they point at.
    """
    names_by_parser = {}
    for name, parser in action.choices.items():
        names_by_parser.setdefault(id(parser), []).append(name)

    out = []
    for pa in action._choices_actions:
        canonical = pa.dest
        parser = action.choices[canonical]
        aliases = [n for n in names_by_parser.get(id(parser), []) if n != canonical]
        out.append({
            "name": canonical,
            "aliases": aliases,
            "help": " ".join((pa.help or "").split()),
            "parser": parser,
        })
    return out


def _flags(parser):
    """Every option string registered directly on `parser`, order-preserving unique."""
    seen = set()
    out = []
    for action in parser._actions:
        for opt in action.option_strings:
            if opt not in seen:
                seen.add(opt)
                out.append(opt)
    return out


def _walk_parser(parser):
    """Build a completion model from a fully-populated parser.

    Returns ``{"flags": [top-level flags], "commands": [ {name, aliases, help,
    flags, subcommands: [ {name, aliases, help, flags} ]} ]}``. Nested subparsers
    (config/secret) are walked one level deep, which covers the whole CLI.
    """
    commands = []
    action = _find_subparsers(parser)
    if action is not None:
        for sc in _subcommands(action):
            nested_action = _find_subparsers(sc["parser"])
            subs = []
            if nested_action is not None:
                for nsc in _subcommands(nested_action):
                    subs.append({
                        "name": nsc["name"],
                        "aliases": nsc["aliases"],
                        "help": nsc["help"],
                        "flags": _flags(nsc["parser"]),
                    })
            commands.append({
                "name": sc["name"],
                "aliases": sc["aliases"],
                "help": sc["help"],
                "flags": _flags(sc["parser"]),
                "subcommands": subs,
            })
    return {"flags": _flags(parser), "commands": commands}


# --------------------------------------------------------------------------- #
# bash
# --------------------------------------------------------------------------- #
def _all_names(cmd):
    return [cmd["name"], *cmd["aliases"]]


def _subtree_flags(cmd):
    """A command's own flags plus every nested action's flags (order-preserving)."""
    seen = set()
    out = []
    for f in cmd["flags"]:
        if f not in seen:
            seen.add(f)
            out.append(f)
    for sub in cmd["subcommands"]:
        for f in sub["flags"]:
            if f not in seen:
                seen.add(f)
                out.append(f)
    return out


def _bash_script(model):
    commands = []
    for cmd in model["commands"]:
        commands.extend(_all_names(cmd))
    global_flags = model["flags"]

    lines = [
        "# bash completion for venice -- generated by `venice completion bash`.",
        "# Load in the current shell:  source <(venice completion bash)",
        "_venice() {",
        "    local cur cword",
        "    COMPREPLY=()",
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        "    cword=$COMP_CWORD",
        "",
        '    local commands="%s"' % " ".join(commands),
        '    local global_flags="%s"' % " ".join(global_flags),
        "",
        '    if [ "$cword" -eq 1 ]; then',
        '        if [[ "$cur" == -* ]]; then',
        '            COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") )',
        "        else",
        '            COMPREPLY=( $(compgen -W "$commands" -- "$cur") )',
        "        fi",
        "        return 0",
        "    fi",
        "",
        '    local cmd="${COMP_WORDS[1]}"',
    ]

    # Nested-subcommand handling (config/secret): complete actions at depth 2.
    nested = [c for c in model["commands"] if c["subcommands"]]
    if nested:
        lines.append('    case "$cmd" in')
        for cmd in nested:
            action_names = []
            for sub in cmd["subcommands"]:
                action_names.extend(_all_names(sub))
            lines += [
                "        %s)" % cmd["name"],
                '            if [ "$cword" -eq 2 ] && [[ "$cur" != -* ]]; then',
                '                COMPREPLY=( $(compgen -W "%s" -- "$cur") )'
                % " ".join(action_names),
                "                return 0",
                "            fi",
                '            COMPREPLY=( $(compgen -W "%s" -- "$cur") )'
                % " ".join(_subtree_flags(cmd)),
                "            return 0",
                "            ;;",
            ]
        lines.append("    esac")
        lines.append("")

    # Per-command flag completion.
    lines.append('    local flags="$global_flags"')
    lines.append('    case "$cmd" in')
    for cmd in model["commands"]:
        if cmd["subcommands"]:
            continue  # handled above
        flags = cmd["flags"] or global_flags
        lines.append('        %s) flags="%s" ;;' % (cmd["name"], " ".join(flags)))
    lines += [
        "    esac",
        '    COMPREPLY=( $(compgen -W "$flags" -- "$cur") )',
        "    return 0",
        "}",
        "complete -F _venice venice",
        "",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# zsh
# --------------------------------------------------------------------------- #
def _zsh_desc(text):
    """Sanitize help text for a zsh `_describe` 'name:description' entry."""
    # ':' and "'" break the entry / the single-quoted string; drop them.
    return text.replace(":", " -").replace("'", "").strip()


def _zsh_describe_block(indent, var, label, items):
    pad = " " * indent
    lines = [f"{pad}local -a {var}", f"{pad}{var}=("]
    for it in items:
        desc = _zsh_desc(it["help"])
        for name in _all_names(it):
            lines.append(f"{pad}    '{name}:{desc}'")
    lines.append(f"{pad})")
    lines.append(f"{pad}_describe -t {var} '{label}' {var}")
    return lines


def _zsh_script(model):
    lines = [
        "#compdef venice",
        "# zsh completion for venice -- generated by `venice completion zsh`.",
        "# Install: venice completion zsh > \"${fpath[1]}/_venice\"  (then restart zsh)",
        "_venice() {",
    ]

    # Depth 1: top-level commands with descriptions.
    lines += [
        "    if (( CURRENT == 2 )); then",
        *_zsh_describe_block(8, "_venice_cmds", "venice command", model["commands"]),
        "        return",
        "    fi",
        "",
        "    local cmd=${words[2]}",
    ]

    nested = [c for c in model["commands"] if c["subcommands"]]
    if nested:
        lines.append("    case $cmd in")
        for cmd in nested:
            lines += [
                f"        {cmd['name']})",
                "            if (( CURRENT == 3 )); then",
                *_zsh_describe_block(16, "_venice_sub", f"{cmd['name']} action",
                                     cmd["subcommands"]),
                "                return",
                "            fi",
                "            compadd -- %s" % " ".join(_subtree_flags(cmd)),
                "            return",
                "            ;;",
            ]
        lines.append("    esac")
        lines.append("")

    # Depth 2+: per-command flag names.
    lines.append("    case $cmd in")
    for cmd in model["commands"]:
        if cmd["subcommands"]:
            continue
        flags = cmd["flags"] or model["flags"]
        lines.append("        %s) compadd -- %s ;;"
                     % (cmd["name"], " ".join(flags)))
    lines += [
        "        *) compadd -- %s ;;" % " ".join(model["flags"]),
        "    esac",
        "}",
        '_venice "$@"',
        "",
    ]
    return "\n".join(lines)
